FROM php:7.2.2-fpm

RUN apt-get update && apt-get install --yes --no-install-recommends libpq-dev git unzip curl && docker-php-ext-install pdo_pgsql pdo_mysql

RUN php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer;